const DataQLphong =[
    {
        Maphong: "V-A030092001",
        name: "Ngô Văn Hiếu",
        phone: "0787314023",
        Tinhtrang: " Ổn Định ",
        TinhtrangVS: "Phòng Sạch",
        nameroom: 230,
        thanhtoan: 100,
      },
      {
        Maphong: "V-A030092002",
        name: "Đang sửa chửa",
        phone: "Đang sửa chửa",
        Tinhtrang: " Đang sửa chửa",
        TinhtrangVS: "Đang sửa chửa",
        nameroom: 230,
        thanhtoan: 100,
      },
      {
        Maphong: "V-A030092002",
        name: "Tuấn Béo",
        phone: "078878023",
        Tinhtrang: " Ổn Định ",
        TinhtrangVS: "Phòng Sạch",
        nameroom: 230,
        thanhtoan: 100,
      },
      {
        Maphong: "V-A030092004",
        name: "A Phú & Chị Duật",
        phone: "2342342324",
        Tinhtrang: " Ổn Định ",
        TinhtrangVS: "Phòng Bẩn",
        nameroom: 230,
        thanhtoan: 100,
      },
      {
        Maphong: "V-A030092008",
        name: "Lê Tiến Tài ",
        phone: "023424023",
        Tinhtrang: " Ổn Định ",
        TinhtrangVS: "Phòng Sạch",
        nameroom: 230,
        thanhtoan: 100,
      },
      {
        Maphong: "V-A030092001",
        name: "Phạm Thị Thu Thảo",
        phone: "0905341332",
        Tinhtrang: " Ổn Định ",
        TinhtrangVS: "Phòng Bẩn",
        nameroom: 230,
        thanhtoan: 300,
      },
      {
        Maphong: "V-A030092230",
        name: "Nguyễn Thị Thanh Phương",
        phone: "0787314023",
        Tinhtrang: " Ổn Định ",
        TinhtrangVS: "Phòng Sạch",
        nameroom: 314,
        thanhtoan: 320,
      },
      {
        Maphong: "V-A030092233",
        name: "Nguyễn Hữu Hải ",
        phone: "09212312311",
        Tinhtrang: " Ổn Định ",
        TinhtrangVS: "Phòng Sạch",
        nameroom: 333,
        thanhtoan: 200,
      },
      {
        Maphong: "V-A030092000",
        name: "Đang sửa chữa",
        phone: "Đang sửa chửa",
        Tinhtrang: " Đang sửa chữa",
        TinhtrangVS: "Đang sửa chữa",
        nameroom: 130,
        thanhtoan: 100,
      },
      {
        Maphong: "V-A030092089",
        name: "Dịp Huỳnh Bảo Bảo",
        phone: "123123123",
        Tinhtrang: " Ổn Định ",
        TinhtrangVS: "Phòng Sạch",
        nameroom: 330,
        thanhtoan: 300,
      },
]

export default DataQLphong