const DataQLdichvu =[
    {
        Maphong: "V-A030092001",
        name: "Ngô Văn Hiếu",
        thucan: "đồ ăn sáng",
        thucuong: "nước cam",
        soluong: "2 người",
        nameroom: 230,
        thanhtoan: 100,
      },
      {
        Maphong: "V-A030092002",
        name: "a Tùng & sự cô đơn",
        thucan: "đồ ăn Trưa",
        thucuong: "rượu Vang Trắng",
        soluong: "1 người",
        nameroom: 230,
        thanhtoan: 500,
      },
      {
        Maphong: "V-A030092002",
        name: "Tuấn Béo",
        thucan: "đồ ăn Tối",
        thucuong: "cam ép không đá , ít đường",
        soluong: "1 người",
        nameroom: 230,
        thanhtoan: 100,
      },
      {
        Maphong: "V-A030092004",
        name: "A Phú & Chị Duật",
        thucan: "đồ ăn cả ngày",
        thucuong: "rượu vang đỏ",
        soluong: "2 người",
        nameroom: 230,
        thanhtoan: 500,
      },
      {
        Maphong: "V-A030092008",
        name: "Lê Tiến Tài ",
        thucan: "đồ ăn trưa",
        thucuong: " capuchino & Coffee Sữa ",
        soluong: "2 người",
        nameroom: 230,
        thanhtoan: 300,
      },
      {
        Maphong: "V-A030092001",
        name: "Phạm Thị Thu Thảo",
        thucan: "đồ ăn sáng",
        thucuong: "Trà sữa 50% ice & 70% sugar",
        soluong: "1 người",
        nameroom: 230,
        thanhtoan: 100,
      },
      {
        Maphong: "V-A030092230",
        name: "Nguyễn Thị Thanh Phương",
        thucan: "đồ ăn Trưa ",
        thucuong: "nước cam",
        soluong: "2 người",
        nameroom: 230,
        thanhtoan: 100,
      },
      {
        Maphong: "V-A030092233",
        name: "Nguyễn Hữu Hải ",
        thucan: "đồ ăn sáng",
        thucuong: "Coffee đen",
        soluong: "2 người",
        nameroom: 230,
        thanhtoan: 100,
      },
      {
        Maphong: "V-A030092000",
        name: "Phạm Thị Trúc Thảo",
        thucan: "đồ ăn trưa",
        thucuong: "nước cam",
        soluong: "2 người",
        nameroom: 230,
        thanhtoan: 100,
      },
      {
        Maphong: "V-A030092089",
        name: "Dịp Huỳnh Bảo Bảo",
        thucan: "đồ ăn Tối",
        thucuong: "nước thơm",
        soluong: "2 người",
        nameroom: 230,
        thanhtoan: 100,
      },
]

export default DataQLdichvu